// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace QA.Engine.Administration.WebApp.Controllers
{
    public partial class SiteMapController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public SiteMapController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected SiteMapController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AjaxTree()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxTree);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AjaxArchiveTree()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxArchiveTree);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AjaxGetItem()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxGetItem);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AjaxTreeMoveItem()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxTreeMoveItem);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AjaxTreeReorderItem()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxTreeReorderItem);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AjaxPublishItem()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxPublishItem);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AjaxAdd()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxAdd);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AjaxEdit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxEdit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AjaxEditItem()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxEditItem);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AjaxGetSiteMap()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxGetSiteMap);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AjaxUpdateItemRegions()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxUpdateItemRegions);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AjaxDeleteItemRegion()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxDeleteItemRegion);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AjaxItemRegionIds()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxItemRegionIds);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AjaxItemCultureIds()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxItemCultureIds);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AjaxCultures()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxCultures);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AjaxRemove()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxRemove);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AjaxRemoveItem()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxRemoveItem);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AjaxDelete()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxDelete);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AjaxDeleteItem()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxDeleteItem);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AjaxRemoveContentVersion()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxRemoveContentVersion);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AjaxRestore()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxRestore);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AjaxRestoreItem()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxRestoreItem);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Info()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Info);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ArchiveInfo()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ArchiveInfo);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Regions()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Regions);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AjaxRegionsGroups()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxRegionsGroups);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AjaxRegions()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxRegions);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AjaxContentVersionsRegions()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxContentVersionsRegions);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Widgets()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Widgets);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AjaxWidgets()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxWidgets);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AjaxPublishWidgetsByAbstractItem()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxPublishWidgetsByAbstractItem);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AjaxPublishWidgets()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxPublishWidgets);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ContentVersions()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ContentVersions);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AjaxContentVersions()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxContentVersions);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public SiteMapController Actions { get { return MVC.SiteMap; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "SiteMap";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "SiteMap";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Archive = "Archive";
            public readonly string AjaxTree = "AjaxTree";
            public readonly string AjaxArchiveTree = "AjaxArchiveTree";
            public readonly string AjaxGetItem = "AjaxGetItem";
            public readonly string AjaxTreeMoveItem = "AjaxTreeMoveItem";
            public readonly string Filter = "Filter";
            public readonly string Toolbar = "Toolbar";
            public readonly string AjaxTreeReorderItem = "AjaxTreeReorderItem";
            public readonly string AjaxPublishItem = "AjaxPublishItem";
            public readonly string AjaxAdd = "AjaxAdd";
            public readonly string AjaxEdit = "AjaxEdit";
            public readonly string AjaxEditItem = "AjaxEditItem";
            public readonly string AjaxMove = "AjaxMove";
            public readonly string AjaxGetSiteMap = "AjaxGetSiteMap";
            public readonly string AjaxUpdateItemRegions = "AjaxUpdateItemRegions";
            public readonly string AjaxDeleteItemRegion = "AjaxDeleteItemRegion";
            public readonly string AjaxItemRegionIds = "AjaxItemRegionIds";
            public readonly string AjaxItemCultureIds = "AjaxItemCultureIds";
            public readonly string AjaxCultures = "AjaxCultures";
            public readonly string AjaxRemove = "AjaxRemove";
            public readonly string AjaxRemoveItem = "AjaxRemoveItem";
            public readonly string AjaxDelete = "AjaxDelete";
            public readonly string AjaxDeleteItem = "AjaxDeleteItem";
            public readonly string AjaxRemoveContentVersion = "AjaxRemoveContentVersion";
            public readonly string AjaxRestore = "AjaxRestore";
            public readonly string AjaxRestoreItem = "AjaxRestoreItem";
            public readonly string Info = "Info";
            public readonly string ArchiveInfo = "ArchiveInfo";
            public readonly string Regions = "Regions";
            public readonly string AjaxRegionsGroups = "AjaxRegionsGroups";
            public readonly string AjaxRegions = "AjaxRegions";
            public readonly string AjaxContentVersionsRegions = "AjaxContentVersionsRegions";
            public readonly string Widgets = "Widgets";
            public readonly string AjaxWidgets = "AjaxWidgets";
            public readonly string AjaxPublishWidgetsByAbstractItem = "AjaxPublishWidgetsByAbstractItem";
            public readonly string AjaxPublishWidgets = "AjaxPublishWidgets";
            public readonly string ContentVersions = "ContentVersions";
            public readonly string AjaxContentVersions = "AjaxContentVersions";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Archive = "Archive";
            public const string AjaxTree = "AjaxTree";
            public const string AjaxArchiveTree = "AjaxArchiveTree";
            public const string AjaxGetItem = "AjaxGetItem";
            public const string AjaxTreeMoveItem = "AjaxTreeMoveItem";
            public const string Filter = "Filter";
            public const string Toolbar = "Toolbar";
            public const string AjaxTreeReorderItem = "AjaxTreeReorderItem";
            public const string AjaxPublishItem = "AjaxPublishItem";
            public const string AjaxAdd = "AjaxAdd";
            public const string AjaxEdit = "AjaxEdit";
            public const string AjaxEditItem = "AjaxEditItem";
            public const string AjaxMove = "AjaxMove";
            public const string AjaxGetSiteMap = "AjaxGetSiteMap";
            public const string AjaxUpdateItemRegions = "AjaxUpdateItemRegions";
            public const string AjaxDeleteItemRegion = "AjaxDeleteItemRegion";
            public const string AjaxItemRegionIds = "AjaxItemRegionIds";
            public const string AjaxItemCultureIds = "AjaxItemCultureIds";
            public const string AjaxCultures = "AjaxCultures";
            public const string AjaxRemove = "AjaxRemove";
            public const string AjaxRemoveItem = "AjaxRemoveItem";
            public const string AjaxDelete = "AjaxDelete";
            public const string AjaxDeleteItem = "AjaxDeleteItem";
            public const string AjaxRemoveContentVersion = "AjaxRemoveContentVersion";
            public const string AjaxRestore = "AjaxRestore";
            public const string AjaxRestoreItem = "AjaxRestoreItem";
            public const string Info = "Info";
            public const string ArchiveInfo = "ArchiveInfo";
            public const string Regions = "Regions";
            public const string AjaxRegionsGroups = "AjaxRegionsGroups";
            public const string AjaxRegions = "AjaxRegions";
            public const string AjaxContentVersionsRegions = "AjaxContentVersionsRegions";
            public const string Widgets = "Widgets";
            public const string AjaxWidgets = "AjaxWidgets";
            public const string AjaxPublishWidgetsByAbstractItem = "AjaxPublishWidgetsByAbstractItem";
            public const string AjaxPublishWidgets = "AjaxPublishWidgets";
            public const string ContentVersions = "ContentVersions";
            public const string AjaxContentVersions = "AjaxContentVersions";
        }


        static readonly ActionParamsClass_AjaxTree s_params_AjaxTree = new ActionParamsClass_AjaxTree();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AjaxTree AjaxTreeParams { get { return s_params_AjaxTree; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AjaxTree
        {
            public readonly string filter = "filter";
        }
        static readonly ActionParamsClass_AjaxArchiveTree s_params_AjaxArchiveTree = new ActionParamsClass_AjaxArchiveTree();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AjaxArchiveTree AjaxArchiveTreeParams { get { return s_params_AjaxArchiveTree; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AjaxArchiveTree
        {
            public readonly string filter = "filter";
        }
        static readonly ActionParamsClass_AjaxGetItem s_params_AjaxGetItem = new ActionParamsClass_AjaxGetItem();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AjaxGetItem AjaxGetItemParams { get { return s_params_AjaxGetItem; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AjaxGetItem
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_AjaxTreeMoveItem s_params_AjaxTreeMoveItem = new ActionParamsClass_AjaxTreeMoveItem();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AjaxTreeMoveItem AjaxTreeMoveItemParams { get { return s_params_AjaxTreeMoveItem; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AjaxTreeMoveItem
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_AjaxTreeReorderItem s_params_AjaxTreeReorderItem = new ActionParamsClass_AjaxTreeReorderItem();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AjaxTreeReorderItem AjaxTreeReorderItemParams { get { return s_params_AjaxTreeReorderItem; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AjaxTreeReorderItem
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_AjaxPublishItem s_params_AjaxPublishItem = new ActionParamsClass_AjaxPublishItem();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AjaxPublishItem AjaxPublishItemParams { get { return s_params_AjaxPublishItem; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AjaxPublishItem
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_AjaxAdd s_params_AjaxAdd = new ActionParamsClass_AjaxAdd();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AjaxAdd AjaxAddParams { get { return s_params_AjaxAdd; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AjaxAdd
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_AjaxEdit s_params_AjaxEdit = new ActionParamsClass_AjaxEdit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AjaxEdit AjaxEditParams { get { return s_params_AjaxEdit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AjaxEdit
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_AjaxEditItem s_params_AjaxEditItem = new ActionParamsClass_AjaxEditItem();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AjaxEditItem AjaxEditItemParams { get { return s_params_AjaxEditItem; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AjaxEditItem
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_AjaxGetSiteMap s_params_AjaxGetSiteMap = new ActionParamsClass_AjaxGetSiteMap();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AjaxGetSiteMap AjaxGetSiteMapParams { get { return s_params_AjaxGetSiteMap; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AjaxGetSiteMap
        {
            public readonly string name = "name";
            public readonly string parentId = "parentId";
        }
        static readonly ActionParamsClass_AjaxUpdateItemRegions s_params_AjaxUpdateItemRegions = new ActionParamsClass_AjaxUpdateItemRegions();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AjaxUpdateItemRegions AjaxUpdateItemRegionsParams { get { return s_params_AjaxUpdateItemRegions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AjaxUpdateItemRegions
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_AjaxDeleteItemRegion s_params_AjaxDeleteItemRegion = new ActionParamsClass_AjaxDeleteItemRegion();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AjaxDeleteItemRegion AjaxDeleteItemRegionParams { get { return s_params_AjaxDeleteItemRegion; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AjaxDeleteItemRegion
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_AjaxItemRegionIds s_params_AjaxItemRegionIds = new ActionParamsClass_AjaxItemRegionIds();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AjaxItemRegionIds AjaxItemRegionIdsParams { get { return s_params_AjaxItemRegionIds; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AjaxItemRegionIds
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_AjaxItemCultureIds s_params_AjaxItemCultureIds = new ActionParamsClass_AjaxItemCultureIds();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AjaxItemCultureIds AjaxItemCultureIdsParams { get { return s_params_AjaxItemCultureIds; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AjaxItemCultureIds
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_AjaxCultures s_params_AjaxCultures = new ActionParamsClass_AjaxCultures();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AjaxCultures AjaxCulturesParams { get { return s_params_AjaxCultures; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AjaxCultures
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_AjaxRemove s_params_AjaxRemove = new ActionParamsClass_AjaxRemove();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AjaxRemove AjaxRemoveParams { get { return s_params_AjaxRemove; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AjaxRemove
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_AjaxRemoveItem s_params_AjaxRemoveItem = new ActionParamsClass_AjaxRemoveItem();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AjaxRemoveItem AjaxRemoveItemParams { get { return s_params_AjaxRemoveItem; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AjaxRemoveItem
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_AjaxDelete s_params_AjaxDelete = new ActionParamsClass_AjaxDelete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AjaxDelete AjaxDeleteParams { get { return s_params_AjaxDelete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AjaxDelete
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_AjaxDeleteItem s_params_AjaxDeleteItem = new ActionParamsClass_AjaxDeleteItem();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AjaxDeleteItem AjaxDeleteItemParams { get { return s_params_AjaxDeleteItem; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AjaxDeleteItem
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_AjaxRemoveContentVersion s_params_AjaxRemoveContentVersion = new ActionParamsClass_AjaxRemoveContentVersion();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AjaxRemoveContentVersion AjaxRemoveContentVersionParams { get { return s_params_AjaxRemoveContentVersion; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AjaxRemoveContentVersion
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_AjaxRestore s_params_AjaxRestore = new ActionParamsClass_AjaxRestore();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AjaxRestore AjaxRestoreParams { get { return s_params_AjaxRestore; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AjaxRestore
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_AjaxRestoreItem s_params_AjaxRestoreItem = new ActionParamsClass_AjaxRestoreItem();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AjaxRestoreItem AjaxRestoreItemParams { get { return s_params_AjaxRestoreItem; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AjaxRestoreItem
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_Info s_params_Info = new ActionParamsClass_Info();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Info InfoParams { get { return s_params_Info; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Info
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_ArchiveInfo s_params_ArchiveInfo = new ActionParamsClass_ArchiveInfo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ArchiveInfo ArchiveInfoParams { get { return s_params_ArchiveInfo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ArchiveInfo
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_Regions s_params_Regions = new ActionParamsClass_Regions();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Regions RegionsParams { get { return s_params_Regions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Regions
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_AjaxRegionsGroups s_params_AjaxRegionsGroups = new ActionParamsClass_AjaxRegionsGroups();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AjaxRegionsGroups AjaxRegionsGroupsParams { get { return s_params_AjaxRegionsGroups; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AjaxRegionsGroups
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_AjaxRegions s_params_AjaxRegions = new ActionParamsClass_AjaxRegions();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AjaxRegions AjaxRegionsParams { get { return s_params_AjaxRegions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AjaxRegions
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_AjaxContentVersionsRegions s_params_AjaxContentVersionsRegions = new ActionParamsClass_AjaxContentVersionsRegions();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AjaxContentVersionsRegions AjaxContentVersionsRegionsParams { get { return s_params_AjaxContentVersionsRegions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AjaxContentVersionsRegions
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_Widgets s_params_Widgets = new ActionParamsClass_Widgets();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Widgets WidgetsParams { get { return s_params_Widgets; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Widgets
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_AjaxWidgets s_params_AjaxWidgets = new ActionParamsClass_AjaxWidgets();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AjaxWidgets AjaxWidgetsParams { get { return s_params_AjaxWidgets; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AjaxWidgets
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_AjaxPublishWidgetsByAbstractItem s_params_AjaxPublishWidgetsByAbstractItem = new ActionParamsClass_AjaxPublishWidgetsByAbstractItem();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AjaxPublishWidgetsByAbstractItem AjaxPublishWidgetsByAbstractItemParams { get { return s_params_AjaxPublishWidgetsByAbstractItem; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AjaxPublishWidgetsByAbstractItem
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_AjaxPublishWidgets s_params_AjaxPublishWidgets = new ActionParamsClass_AjaxPublishWidgets();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AjaxPublishWidgets AjaxPublishWidgetsParams { get { return s_params_AjaxPublishWidgets; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AjaxPublishWidgets
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_ContentVersions s_params_ContentVersions = new ActionParamsClass_ContentVersions();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ContentVersions ContentVersionsParams { get { return s_params_ContentVersions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ContentVersions
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_AjaxContentVersions s_params_AjaxContentVersions = new ActionParamsClass_AjaxContentVersions();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AjaxContentVersions AjaxContentVersionsParams { get { return s_params_AjaxContentVersions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AjaxContentVersions
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string AjaxAdd = "AjaxAdd";
                public readonly string AjaxDelete = "AjaxDelete";
                public readonly string AjaxEdit = "AjaxEdit";
                public readonly string AjaxMove = "AjaxMove";
                public readonly string AjaxRemove = "AjaxRemove";
                public readonly string AjaxRestore = "AjaxRestore";
                public readonly string Archive = "Archive";
                public readonly string ArchiveInfo = "ArchiveInfo";
                public readonly string ContentVersions = "ContentVersions";
                public readonly string Filter = "Filter";
                public readonly string Index = "Index";
                public readonly string Info = "Info";
                public readonly string Regions = "Regions";
                public readonly string Toolbar = "Toolbar";
                public readonly string Widgets = "Widgets";
            }
            public readonly string AjaxAdd = "~/Views/SiteMap/AjaxAdd.cshtml";
            public readonly string AjaxDelete = "~/Views/SiteMap/AjaxDelete.cshtml";
            public readonly string AjaxEdit = "~/Views/SiteMap/AjaxEdit.cshtml";
            public readonly string AjaxMove = "~/Views/SiteMap/AjaxMove.cshtml";
            public readonly string AjaxRemove = "~/Views/SiteMap/AjaxRemove.cshtml";
            public readonly string AjaxRestore = "~/Views/SiteMap/AjaxRestore.cshtml";
            public readonly string Archive = "~/Views/SiteMap/Archive.cshtml";
            public readonly string ArchiveInfo = "~/Views/SiteMap/ArchiveInfo.cshtml";
            public readonly string ContentVersions = "~/Views/SiteMap/ContentVersions.cshtml";
            public readonly string Filter = "~/Views/SiteMap/Filter.cshtml";
            public readonly string Index = "~/Views/SiteMap/Index.cshtml";
            public readonly string Info = "~/Views/SiteMap/Info.cshtml";
            public readonly string Regions = "~/Views/SiteMap/Regions.cshtml";
            public readonly string Toolbar = "~/Views/SiteMap/Toolbar.cshtml";
            public readonly string Widgets = "~/Views/SiteMap/Widgets.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_SiteMapController : QA.Engine.Administration.WebApp.Controllers.SiteMapController
    {
        public T4MVC_SiteMapController() : base(Dummy.Instance) { }

        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        partial void ArchiveOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Archive()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Archive);
            ArchiveOverride(callInfo);
            return callInfo;
        }

        partial void AjaxTreeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, QA.Engine.Administration.WebApp.Models.SiteMap.FilterViewModel filter);

        public override System.Web.Mvc.ActionResult AjaxTree(QA.Engine.Administration.WebApp.Models.SiteMap.FilterViewModel filter)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxTree);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "filter", filter);
            AjaxTreeOverride(callInfo, filter);
            return callInfo;
        }

        partial void AjaxArchiveTreeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, QA.Engine.Administration.WebApp.Models.SiteMap.FilterViewModel filter);

        public override System.Web.Mvc.ActionResult AjaxArchiveTree(QA.Engine.Administration.WebApp.Models.SiteMap.FilterViewModel filter)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxArchiveTree);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "filter", filter);
            AjaxArchiveTreeOverride(callInfo, filter);
            return callInfo;
        }

        partial void AjaxGetItemOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, QA.Engine.Administration.WebApp.Models.SiteMap.ReadSiteMapItemViewModel viewModel);

        public override System.Web.Mvc.ActionResult AjaxGetItem(QA.Engine.Administration.WebApp.Models.SiteMap.ReadSiteMapItemViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxGetItem);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            AjaxGetItemOverride(callInfo, viewModel);
            return callInfo;
        }

        partial void AjaxTreeMoveItemOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, QA.Engine.Administration.WebApp.Models.SiteMap.MoveItemViewModel viewModel);

        public override System.Web.Mvc.ActionResult AjaxTreeMoveItem(QA.Engine.Administration.WebApp.Models.SiteMap.MoveItemViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxTreeMoveItem);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            AjaxTreeMoveItemOverride(callInfo, viewModel);
            return callInfo;
        }

        partial void FilterOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Filter()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Filter);
            FilterOverride(callInfo);
            return callInfo;
        }

        partial void ToolbarOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Toolbar()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Toolbar);
            ToolbarOverride(callInfo);
            return callInfo;
        }

        partial void AjaxTreeReorderItemOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, QA.Engine.Administration.WebApp.Models.SiteMap.ReorderViewModel viewModel);

        public override System.Web.Mvc.ActionResult AjaxTreeReorderItem(QA.Engine.Administration.WebApp.Models.SiteMap.ReorderViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxTreeReorderItem);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            AjaxTreeReorderItemOverride(callInfo, viewModel);
            return callInfo;
        }

        partial void AjaxPublishItemOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, QA.Engine.Administration.WebApp.Models.SiteMap.PublishItemViewModel viewModel);

        public override System.Web.Mvc.ActionResult AjaxPublishItem(QA.Engine.Administration.WebApp.Models.SiteMap.PublishItemViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxPublishItem);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            AjaxPublishItemOverride(callInfo, viewModel);
            return callInfo;
        }

        partial void AjaxAddOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, QA.Engine.Administration.WebApp.Models.SiteMap.AddSiteMapViewModel viewModel);

        public override System.Web.Mvc.ActionResult AjaxAdd(QA.Engine.Administration.WebApp.Models.SiteMap.AddSiteMapViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxAdd);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            AjaxAddOverride(callInfo, viewModel);
            return callInfo;
        }

        partial void AjaxEditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, QA.Engine.Administration.WebApp.Models.SiteMap.EditableSiteMapViewModel viewModel);

        public override System.Web.Mvc.ActionResult AjaxEdit(QA.Engine.Administration.WebApp.Models.SiteMap.EditableSiteMapViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxEdit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            AjaxEditOverride(callInfo, viewModel);
            return callInfo;
        }

        partial void AjaxEditItemOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, QA.Engine.Administration.WebApp.Models.SiteMap.EditableSiteMapViewModel viewModel);

        public override System.Web.Mvc.ActionResult AjaxEditItem(QA.Engine.Administration.WebApp.Models.SiteMap.EditableSiteMapViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxEditItem);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            AjaxEditItemOverride(callInfo, viewModel);
            return callInfo;
        }

        partial void AjaxMoveOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult AjaxMove()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxMove);
            AjaxMoveOverride(callInfo);
            return callInfo;
        }

        partial void AjaxGetSiteMapOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string name, int parentId);

        public override System.Web.Mvc.ActionResult AjaxGetSiteMap(string name, int parentId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxGetSiteMap);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "name", name);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "parentId", parentId);
            AjaxGetSiteMapOverride(callInfo, name, parentId);
            return callInfo;
        }

        partial void AjaxUpdateItemRegionsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, QA.Engine.Administration.WebApp.Models.SiteMap.EditableItemRegionList viewModel);

        public override System.Web.Mvc.ActionResult AjaxUpdateItemRegions(QA.Engine.Administration.WebApp.Models.SiteMap.EditableItemRegionList viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxUpdateItemRegions);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            AjaxUpdateItemRegionsOverride(callInfo, viewModel);
            return callInfo;
        }

        partial void AjaxDeleteItemRegionOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, QA.Engine.Administration.WebApp.Models.SiteMap.DeleteSiteMapRegionViewModel viewModel);

        public override System.Web.Mvc.ActionResult AjaxDeleteItemRegion(QA.Engine.Administration.WebApp.Models.SiteMap.DeleteSiteMapRegionViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxDeleteItemRegion);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            AjaxDeleteItemRegionOverride(callInfo, viewModel);
            return callInfo;
        }

        partial void AjaxItemRegionIdsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, QA.Engine.Administration.WebApp.Models.SimpleViewModel<int> viewModel);

        public override System.Web.Mvc.ActionResult AjaxItemRegionIds(QA.Engine.Administration.WebApp.Models.SimpleViewModel<int> viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxItemRegionIds);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            AjaxItemRegionIdsOverride(callInfo, viewModel);
            return callInfo;
        }

        partial void AjaxItemCultureIdsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, QA.Engine.Administration.WebApp.Models.SimpleViewModel<int> viewModel);

        public override System.Web.Mvc.ActionResult AjaxItemCultureIds(QA.Engine.Administration.WebApp.Models.SimpleViewModel<int> viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxItemCultureIds);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            AjaxItemCultureIdsOverride(callInfo, viewModel);
            return callInfo;
        }

        partial void AjaxCulturesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, QA.Engine.Administration.WebApp.Models.SimpleViewModel<int> viewModel);

        public override System.Web.Mvc.ActionResult AjaxCultures(QA.Engine.Administration.WebApp.Models.SimpleViewModel<int> viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxCultures);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            AjaxCulturesOverride(callInfo, viewModel);
            return callInfo;
        }

        partial void AjaxRemoveOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, QA.Engine.Administration.WebApp.Models.SiteMap.RemoveSiteMapViewModel viewModel);

        public override System.Web.Mvc.ActionResult AjaxRemove(QA.Engine.Administration.WebApp.Models.SiteMap.RemoveSiteMapViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxRemove);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            AjaxRemoveOverride(callInfo, viewModel);
            return callInfo;
        }

        partial void AjaxRemoveItemOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, QA.Engine.Administration.WebApp.Models.SiteMap.RemoveSiteMapViewModel viewModel);

        public override System.Web.Mvc.ActionResult AjaxRemoveItem(QA.Engine.Administration.WebApp.Models.SiteMap.RemoveSiteMapViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxRemoveItem);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            AjaxRemoveItemOverride(callInfo, viewModel);
            return callInfo;
        }

        partial void AjaxDeleteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, QA.Engine.Administration.WebApp.Models.SiteMap.DeleteSiteMapViewModel viewModel);

        public override System.Web.Mvc.ActionResult AjaxDelete(QA.Engine.Administration.WebApp.Models.SiteMap.DeleteSiteMapViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxDelete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            AjaxDeleteOverride(callInfo, viewModel);
            return callInfo;
        }

        partial void AjaxDeleteItemOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, QA.Engine.Administration.WebApp.Models.SiteMap.DeleteSiteMapViewModel viewModel);

        public override System.Web.Mvc.ActionResult AjaxDeleteItem(QA.Engine.Administration.WebApp.Models.SiteMap.DeleteSiteMapViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxDeleteItem);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            AjaxDeleteItemOverride(callInfo, viewModel);
            return callInfo;
        }

        partial void AjaxRemoveContentVersionOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, QA.Engine.Administration.WebApp.Models.SiteMap.RemoveSiteMapViewModel viewModel);

        public override System.Web.Mvc.ActionResult AjaxRemoveContentVersion(QA.Engine.Administration.WebApp.Models.SiteMap.RemoveSiteMapViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxRemoveContentVersion);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            AjaxRemoveContentVersionOverride(callInfo, viewModel);
            return callInfo;
        }

        partial void AjaxRestoreOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, QA.Engine.Administration.WebApp.Models.SiteMap.RestoreSiteMapViewModel viewModel);

        public override System.Web.Mvc.ActionResult AjaxRestore(QA.Engine.Administration.WebApp.Models.SiteMap.RestoreSiteMapViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxRestore);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            AjaxRestoreOverride(callInfo, viewModel);
            return callInfo;
        }

        partial void AjaxRestoreItemOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, QA.Engine.Administration.WebApp.Models.SiteMap.RestoreSiteMapViewModel viewModel);

        public override System.Web.Mvc.ActionResult AjaxRestoreItem(QA.Engine.Administration.WebApp.Models.SiteMap.RestoreSiteMapViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxRestoreItem);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            AjaxRestoreItemOverride(callInfo, viewModel);
            return callInfo;
        }

        partial void InfoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, QA.Engine.Administration.WebApp.Models.SiteMap.ReadInfoViewModel viewModel);

        public override System.Web.Mvc.ActionResult Info(QA.Engine.Administration.WebApp.Models.SiteMap.ReadInfoViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Info);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            InfoOverride(callInfo, viewModel);
            return callInfo;
        }

        partial void ArchiveInfoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, QA.Engine.Administration.WebApp.Models.SiteMap.ReadInfoViewModel viewModel);

        public override System.Web.Mvc.ActionResult ArchiveInfo(QA.Engine.Administration.WebApp.Models.SiteMap.ReadInfoViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ArchiveInfo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            ArchiveInfoOverride(callInfo, viewModel);
            return callInfo;
        }

        partial void RegionsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, QA.Engine.Administration.WebApp.Models.SiteMap.ReadRegionsViewModel viewModel);

        public override System.Web.Mvc.ActionResult Regions(QA.Engine.Administration.WebApp.Models.SiteMap.ReadRegionsViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Regions);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            RegionsOverride(callInfo, viewModel);
            return callInfo;
        }

        partial void AjaxRegionsGroupsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, QA.Engine.Administration.WebApp.Models.SiteMap.ReadRegionsViewModel viewModel);

        public override System.Web.Mvc.ActionResult AjaxRegionsGroups(QA.Engine.Administration.WebApp.Models.SiteMap.ReadRegionsViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxRegionsGroups);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            AjaxRegionsGroupsOverride(callInfo, viewModel);
            return callInfo;
        }

        partial void AjaxRegionsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, QA.Engine.Administration.WebApp.Models.SiteMap.ReadRegionsViewModel viewModel);

        public override System.Web.Mvc.ActionResult AjaxRegions(QA.Engine.Administration.WebApp.Models.SiteMap.ReadRegionsViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxRegions);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            AjaxRegionsOverride(callInfo, viewModel);
            return callInfo;
        }

        partial void AjaxContentVersionsRegionsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, QA.Engine.Administration.WebApp.Models.SiteMap.ReadRegionsViewModel viewModel);

        public override System.Web.Mvc.ActionResult AjaxContentVersionsRegions(QA.Engine.Administration.WebApp.Models.SiteMap.ReadRegionsViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxContentVersionsRegions);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            AjaxContentVersionsRegionsOverride(callInfo, viewModel);
            return callInfo;
        }

        partial void WidgetsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, QA.Engine.Administration.WebApp.Models.SiteMap.ReadWidgetsViewModel viewModel);

        public override System.Web.Mvc.ActionResult Widgets(QA.Engine.Administration.WebApp.Models.SiteMap.ReadWidgetsViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Widgets);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            WidgetsOverride(callInfo, viewModel);
            return callInfo;
        }

        partial void AjaxWidgetsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, QA.Engine.Administration.WebApp.Models.SiteMap.ReadWidgetsViewModel viewModel);

        public override System.Web.Mvc.ActionResult AjaxWidgets(QA.Engine.Administration.WebApp.Models.SiteMap.ReadWidgetsViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxWidgets);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            AjaxWidgetsOverride(callInfo, viewModel);
            return callInfo;
        }

        partial void AjaxPublishWidgetsByAbstractItemOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        public override System.Web.Mvc.ActionResult AjaxPublishWidgetsByAbstractItem(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxPublishWidgetsByAbstractItem);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            AjaxPublishWidgetsByAbstractItemOverride(callInfo, id);
            return callInfo;
        }

        partial void AjaxPublishWidgetsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int[] id);

        public override System.Web.Mvc.ActionResult AjaxPublishWidgets(int[] id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxPublishWidgets);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            AjaxPublishWidgetsOverride(callInfo, id);
            return callInfo;
        }

        partial void ContentVersionsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, QA.Engine.Administration.WebApp.Models.SiteMap.ReadContentVersionsViewModel viewModel);

        public override System.Web.Mvc.ActionResult ContentVersions(QA.Engine.Administration.WebApp.Models.SiteMap.ReadContentVersionsViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ContentVersions);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            ContentVersionsOverride(callInfo, viewModel);
            return callInfo;
        }

        partial void AjaxContentVersionsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, QA.Engine.Administration.WebApp.Models.SiteMap.ReadContentVersionsViewModel viewModel);

        public override System.Web.Mvc.ActionResult AjaxContentVersions(QA.Engine.Administration.WebApp.Models.SiteMap.ReadContentVersionsViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxContentVersions);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            AjaxContentVersionsOverride(callInfo, viewModel);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
