//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Engine.Administration.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QA.Engine.Administration.Services.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указана версия для замены..
        /// </summary>
        internal static string ChangingVersionNotSpecified {
            get {
                return ResourceManager.GetString("ChangingVersionNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контентная версия не найдена..
        /// </summary>
        internal static string ContentVersionNotFound {
            get {
                return ResourceManager.GetString("ContentVersionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя добавлять элемент в контентую версию..
        /// </summary>
        internal static string DenyAddItemToContentVersion {
            get {
                return ResourceManager.GetString("DenyAddItemToContentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя удалить элемент..
        /// </summary>
        internal static string DenyDeleteElement {
            get {
                return ResourceManager.GetString("DenyDeleteElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя удалить главную  страницу..
        /// </summary>
        internal static string DenyDeleteRootPage {
            get {
                return ResourceManager.GetString("DenyDeleteRootPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя переносить элемент в нижние элементы текущей ветки..
        /// </summary>
        internal static string DenyMoveElementToChild {
            get {
                return ResourceManager.GetString("DenyMoveElementToChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя переносить элемент в самого себя..
        /// </summary>
        internal static string DenyMoveElementToItSelf {
            get {
                return ResourceManager.GetString("DenyMoveElementToItSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя переносить элементы разных культур..
        /// </summary>
        internal static string DenyMoveElementToOtherCulture {
            get {
                return ResourceManager.GetString("DenyMoveElementToOtherCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя переносить элемент в другую ветку..
        /// </summary>
        internal static string DenyMoveElementToOtherParent {
            get {
                return ResourceManager.GetString("DenyMoveElementToOtherParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя переносить элементы с разным набором регионов..
        /// </summary>
        internal static string DenyMoveElementToOtherRegion {
            get {
                return ResourceManager.GetString("DenyMoveElementToOtherRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Элемент не может быть перенесен в раздел данного типа..
        /// </summary>
        internal static string DenyMoveElementToWrongType {
            get {
                return ResourceManager.GetString("DenyMoveElementToWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя переносить главную страницу..
        /// </summary>
        internal static string DenyMoveMainPage {
            get {
                return ResourceManager.GetString("DenyMoveMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя переносить стартовую страницу..
        /// </summary>
        internal static string DenyMoveStartPage {
            get {
                return ResourceManager.GetString("DenyMoveStartPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя восстановить элемент без элемента-предка..
        /// </summary>
        internal static string DenyRestoreItemWithoutNonDeleteParentItem {
            get {
                return ResourceManager.GetString("DenyRestoreItemWithoutNonDeleteParentItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Элемент не найден..
        /// </summary>
        internal static string ElementNotFound {
            get {
                return ResourceManager.GetString("ElementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Элемент-предок не найден..
        /// </summary>
        internal static string ParentElementNotFound {
            get {
                return ResourceManager.GetString("ParentElementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найден элемент относительно которого производится перенос..
        /// </summary>
        internal static string ReferenceElementNotFound {
            get {
                return ResourceManager.GetString("ReferenceElementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перемещаемый элемент уже находится в указанном элементе..
        /// </summary>
        internal static string SourceElementHasCurrentParent {
            get {
                return ResourceManager.GetString("SourceElementHasCurrentParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найден элемент для переноса..
        /// </summary>
        internal static string SourceElementNotFound {
            get {
                return ResourceManager.GetString("SourceElementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найден элемент-приемник..
        /// </summary>
        internal static string TargetElementNotFound {
            get {
                return ResourceManager.GetString("TargetElementNotFound", resourceCulture);
            }
        }
    }
}
