//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Engine.Administration.WebApp.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    //[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewModelStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewModelStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QA.Engine.Administration.WebApp.App_LocalResources.ViewModelStrings", typeof(ViewModelStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Языковая культура.
        /// </summary>
        public static string AddSiteMapViewModel_Culture {
            get {
                return ResourceManager.GetString("AddSiteMapViewModel_Culture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполните это поле.
        /// </summary>
        public static string AddSiteMapViewModel_DiscriminatorId_Required {
            get {
                return ResourceManager.GetString("AddSiteMapViewModel_DiscriminatorId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип элемента.
        /// </summary>
        public static string AddSiteMapViewModel_ElementType {
            get {
                return ResourceManager.GetString("AddSiteMapViewModel_ElementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ид..
        /// </summary>
        public static string AddSiteMapViewModel_Id {
            get {
                return ResourceManager.GetString("AddSiteMapViewModel_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отображать на карте сайта.
        /// </summary>
        public static string AddSiteMapViewModel_InSitemap {
            get {
                return ResourceManager.GetString("AddSiteMapViewModel_InSitemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string AddSiteMapViewModel_Name {
            get {
                return ResourceManager.GetString("AddSiteMapViewModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недопустимые символы в названии.
        /// </summary>
        public static string AddSiteMapViewModel_Name_Pattern {
            get {
                return ResourceManager.GetString("AddSiteMapViewModel_Name_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполните это поле.
        /// </summary>
        public static string AddSiteMapViewModel_Name_Required {
            get {
                return ResourceManager.GetString("AddSiteMapViewModel_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальная длина строки {1}.
        /// </summary>
        public static string AddSiteMapViewModel_Name_StringLength {
            get {
                return ResourceManager.GetString("AddSiteMapViewModel_Name_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус статьи.
        /// </summary>
        public static string AddSiteMapViewModel_State {
            get {
                return ResourceManager.GetString("AddSiteMapViewModel_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок.
        /// </summary>
        public static string AddSiteMapViewModel_Title {
            get {
                return ResourceManager.GetString("AddSiteMapViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполните это поле.
        /// </summary>
        public static string AddSiteMapViewModel_Title_Required {
            get {
                return ResourceManager.GetString("AddSiteMapViewModel_Title_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальная длина строки {1}.
        /// </summary>
        public static string AddSiteMapViewModel_Title_StringLength {
            get {
                return ResourceManager.GetString("AddSiteMapViewModel_Title_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип страницы.
        /// </summary>
        public static string AddSiteMapViewModel_Type {
            get {
                return ResourceManager.GetString("AddSiteMapViewModel_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отображать в навигации.
        /// </summary>
        public static string AddSiteMapViewModel_Visible {
            get {
                return ResourceManager.GetString("AddSiteMapViewModel_Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действие над контентными версиями.
        /// </summary>
        public static string ContentVersionOperation_Title {
            get {
                return ResourceManager.GetString("ContentVersionOperation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполните это поле.
        /// </summary>
        public static string DeleteSiteMapViewModel_ContentVersionId_RequiredIf {
            get {
                return ResourceManager.GetString("DeleteSiteMapViewModel_ContentVersionId_RequiredIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить версии.
        /// </summary>
        public static string DeleteVersions_Title {
            get {
                return ResourceManager.GetString("DeleteVersions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстановить подчиненные.
        /// </summary>
        public static string RestoreChildren_Title {
            get {
                return ResourceManager.GetString("RestoreChildren_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстановить контентные версии.
        /// </summary>
        public static string RestoreContentVersions_Title {
            get {
                return ResourceManager.GetString("RestoreContentVersions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстановить версии.
        /// </summary>
        public static string RestoreVersions_Title {
            get {
                return ResourceManager.GetString("RestoreVersions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстановить виджеты.
        /// </summary>
        public static string RestoreWidgets_Title {
            get {
                return ResourceManager.GetString("RestoreWidgets_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия для замены.
        /// </summary>
        public static string VersionToReplace_Title {
            get {
                return ResourceManager.GetString("VersionToReplace_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип версии.
        /// </summary>
        public static string VersionType_Title {
            get {
                return ResourceManager.GetString("VersionType_Title", resourceCulture);
            }
        }
    }
}
