//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Engine.Administration.Data {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QA.Engine.Administration.Data.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Элемент не найден..
        /// </summary>
        internal static string ElementNotFound {
            get {
                return ResourceManager.GetString("ElementNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Не найден элемент для публикации..
        /// </summary>
        internal static string PublishigElementNotFound {
            get {
                return ResourceManager.GetString("PublishigElementNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Не найден статус для публикации..
        /// </summary>
        internal static string PublishingStatusNotFound {
            get {
                return ResourceManager.GetString("PublishingStatusNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Главная страница не найдена..
        /// </summary>
        internal static string RootPageNotFount {
            get {
                return ResourceManager.GetString("RootPageNotFount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Не найден элемент для переноса..
        /// </summary>
        internal static string SourceElementNotFound {
            get {
                return ResourceManager.GetString("SourceElementNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Не найден статус {0}..
        /// </summary>
        internal static string StatusNotFound {
            get {
                return ResourceManager.GetString("StatusNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Не найден элемент-приемник..
        /// </summary>
        internal static string TargetElementNotFound {
            get {
                return ResourceManager.GetString("TargetElementNotFound", resourceCulture);
            }
        }
    }
}
